use dw_future_sales

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_INIT_FACT_SALES]

AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;

------------------------------------------------------------------------------------
-- Bắt đầu Transaction
BEGIN TRAN;
BEGIN TRY;

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'FACT_SALES')
   DROP TABLE dw_future_sales.dbo.FACT_SALES

CREATE TABLE dw_future_sales.dbo.FACT_SALES (
	DATE_KEY BIGINT , -- DIM_DATE
    ITEM_CATEGORY_KEY INT,
    ITEM_KEY INT,
    SHOP_KEY INT,
    UNIT_PRICE DECIMAL(18,2),
    QUANTITY INT,
    SALE_AMOUNT DECIMAL(18,2),
)

ALTER TABLE dbo.FACT_SALES
ADD CONSTRAINT FK_DATE_KEY FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);
ALTER TABLE dbo.FACT_SALES
ADD CONSTRAINT FK_ITEM_CATEGORY_KEY FOREIGN KEY (ITEM_CATEGORY_KEY) REFERENCES DIM_ITEMS_CAT(ITEM_CATEGORY_KEY);
ALTER TABLE dbo.FACT_SALES
ADD CONSTRAINT FK_ITEM_KEY FOREIGN KEY (ITEM_KEY) REFERENCES DIM_ITEM(ITEM_KEY);
ALTER TABLE dbo.FACT_SALES
ADD CONSTRAINT FK_SHOP_KEY FOREIGN KEY (SHOP_KEY) REFERENCES DIM_SHOP(SHOP_KEY);


-- COMMIT HANDLE DATA
COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)
END CATCH

-- Kết thúc Transaction
------------------------------------------------------------------------------------
END

EXEC [dbo].[SP_INIT_FACT_SALES]
GO


