USE dw_future_sales
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_FLOAD_DIM_ITEMS_CAT]
AS
BEGIN

SET NOCOUNT ON
SET XACT_ABORT ON
SET IDENTITY_INSERT dw_future_sales.dbo.DIM_ITEMS_CAT OFF

BEGIN TRAN
BEGIN TRY
    TRUNCATE TABLE dbo.DIM_ITEMS_CAT

    INSERT INTO dbo.DIM_ITEMS_CAT(ITEM_CATEGORY_ID, ITEM_CATEGORY_NAME)
    SELECT DISTINCT ITEM_CATEGORY_ID, ITEM_CATEGORY_NAME
    from [stg].[ITEM_CAT]


COMMIT
RETURN 0
END TRY
BEGIN CATCH
    ROLLBACK
    DECLARE @errormessage NVARCHAR(2000)
    SELECT @errormessage = 'ERROR ' + ERROR_MESSAGE()
    RAISERROR(@errormessage, 16, 1)
END CATCH

END
GO


-- EXEC [dbo].[SP_FLOAD_DIM_ITEMS_CAT]
-- GO

select * from DIM_ITEMS_CAT
