USE dw_future_sales
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_FLOAD_DIM_ITEM]
AS
BEGIN

SET NOCOUNT ON
SET XACT_ABORT ON
SET IDENTITY_INSERT dw_future_sales.dbo.DIM_ITEM OFF

BEGIN TRAN
BEGIN TRY
    TRUNCATE TABLE dbo.DIM_ITEM

    INSERT INTO dbo.DIM_ITEM(ITEM_ID, ITEM_NAME, ITEM_CATEGORY_KEY)
    SELECT DISTINCT
    ITEM_ID,
    ITEM_NAME,
    ITEM_CATEGORY_KEY
    FROM [stg].[ITEM] i
    join dbo.ITEM_CAT ic on i.item_category_id = ic.ITEM_CATEGORY_ID

COMMIT
RETURN 0
END TRY
BEGIN CATCH
    ROLLBACK
    DECLARE @errormessage NVARCHAR(2000)
    SELECT @errormessage = 'ERROR ' + ERROR_MESSAGE()
    RAISERROR(@errormessage, 16, 1)
END CATCH

END
GO

-- EXEC [dbo].[SP_FLOAD_DIM_ITEM]
-- GO
