USE dw_future_sales
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_FLOAD_DIM_SHOP]
AS
BEGIN

SET NOCOUNT ON
SET XACT_ABORT ON
SET IDENTITY_INSERT dw_future_sales.dbo.DIM_SHOP OFF

BEGIN TRAN
BEGIN TRY
    TRUNCATE TABLE dbo.DIM_SHOP

    INSERT INTO dbo.DIM_SHOP(SHOP_ID,SHOP_NAME)
    SELECT DISTINCT
    SHOP_ID,
    SHOP_NAME
    FROM [stg].[SHOP]


COMMIT
RETURN 0
END TRY
BEGIN CATCH
    ROLLBACK
    DECLARE @errormessage NVARCHAR(2000)
    SELECT @errormessage = 'ERROR ' + ERROR_MESSAGE()
    RAISERROR(@errormessage, 16, 1)
END CATCH

END
GO

-- EXEC [dbo].[SP_FLOAD_DIM_SHOP]
-- GO

-- select * from DIM_SHOP
